USE [master]
GO

/****** Object:  Database [LIB]    Script Date: 04/03/2012 01:40:02 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'LIB')
DROP DATABASE [LIB]
GO

USE [master]
GO

/****** Object:  Database [LIB]    Script Date: 04/03/2012 01:40:02 ******/
CREATE DATABASE [LIB] ON  PRIMARY 
( NAME = N'LIB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [LIB_OldData] 
( NAME = N'LIBOldData', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2012.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [LIB_2013] 
( NAME = N'LIB2013', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2013.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [LIB_2014] 
( NAME = N'LIB2014', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2014.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [LIB_2015] 
( NAME = N'LIB2015', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2015.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ),
 FILEGROUP [LIB_2016] 
( NAME = N'LIB2016', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2016.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LIB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LIBOldData_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2012_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LIB2013_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2013_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LIB2014_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2014_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LIB2015_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2015_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'LIB2016_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\LIB2016_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [LIB] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LIB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LIB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LIB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LIB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LIB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LIB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LIB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LIB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [LIB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LIB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LIB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LIB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LIB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LIB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LIB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LIB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LIB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LIB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LIB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LIB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LIB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LIB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LIB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LIB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LIB] SET  READ_WRITE 
GO

ALTER DATABASE [LIB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LIB] SET  MULTI_USER 
GO

ALTER DATABASE [LIB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LIB] SET DB_CHAINING OFF 
GO


