//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LIB.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh mục thất bại !!!.
        /// </summary>
        public static string ADD_CATEGORY_FAIL {
            get {
                return ResourceManager.GetString("ADD_CATEGORY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật danh mục thành công !!!.
        /// </summary>
        public static string ADD_CATEGORY_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_CATEGORY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã danh mục này đã tồn tại, bạn vui lòng nhập mã danh mục khác !!!.
        /// </summary>
        public static string ADD_EXISTING_CATEGORY_ID {
            get {
                return ResourceManager.GetString("ADD_EXISTING_CATEGORY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể để trống Mã danh mục !!!.
        /// </summary>
        public static string ADD_NULL_CATEGORY_ID {
            get {
                return ResourceManager.GetString("ADD_NULL_CATEGORY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên danh mục không thể để trống !!!.
        /// </summary>
        public static string ADD_NULL_CATEGORY_NAME {
            get {
                return ResourceManager.GetString("ADD_NULL_CATEGORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên NXB không thể để trống !!!.
        /// </summary>
        public static string ADD_NULL_PUBLISHER_NAME {
            get {
                return ResourceManager.GetString("ADD_NULL_PUBLISHER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục này không có cha, phải thêm danh mục cha trước!.
        /// </summary>
        public static string ADD_ORPHANAGE_CATEGORY {
            get {
                return ResourceManager.GetString("ADD_ORPHANAGE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm NXB thất bại !!!.
        /// </summary>
        public static string ADD_PUBLISHER_FAIL {
            get {
                return ResourceManager.GetString("ADD_PUBLISHER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm NXB thành công !!!.
        /// </summary>
        public static string ADD_PUBLISHER_SUCCESS {
            get {
                return ResourceManager.GetString("ADD_PUBLISHER_SUCCESS", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap coco_report_banner {
            get {
                object obj = ResourceManager.GetObject("coco-report-banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc là muốn xóa danh mục này không?.
        /// </summary>
        public static string DELETE_CATEGORY_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_CATEGORY_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa danh mục thất bại.
        /// </summary>
        public static string DELETE_CATEGORY_FAIL {
            get {
                return ResourceManager.GetString("DELETE_CATEGORY_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa danh mục thành công.
        /// </summary>
        public static string DELETE_CATEGORY_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_CATEGORY_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá danh mục mặc định. Hãy chọn danh mục khác.
        /// </summary>
        public static string DELETE_DEFAULT_CATEGORY {
            get {
                return ResourceManager.GetString("DELETE_DEFAULT_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xoá Nhà xuất bản mặc định! Hãy chọn Nhà xuất bản khác..
        /// </summary>
        public static string DELETE_DEFAULT_PUBLISHER {
            get {
                return ResourceManager.GetString("DELETE_DEFAULT_PUBLISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một danh mục để xóa !!!.
        /// </summary>
        public static string DELETE_NONE_CATEGORY {
            get {
                return ResourceManager.GetString("DELETE_NONE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn một NXB để thao tác xóa !!!.
        /// </summary>
        public static string DELETE_NONE_PUBLISHER {
            get {
                return ResourceManager.GetString("DELETE_NONE_PUBLISHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc là muốn xóa NXB này không?.
        /// </summary>
        public static string DELETE_PUBLISHER_CONFIRM {
            get {
                return ResourceManager.GetString("DELETE_PUBLISHER_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa NXB thất bại !!!.
        /// </summary>
        public static string DELETE_PUBLISHER_FAIL {
            get {
                return ResourceManager.GetString("DELETE_PUBLISHER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa NXB thành công !!!.
        /// </summary>
        public static string DELETE_PUBLISHER_SUCCESS {
            get {
                return ResourceManager.GetString("DELETE_PUBLISHER_SUCCESS", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap document_chart {
            get {
                object obj = ResourceManager.GetObject("document_chart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        public static System.Drawing.Icon FU_LIB {
            get {
                object obj = ResourceManager.GetObject("FU_LIB", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        public static System.Drawing.Bitmap question1 {
            get {
                object obj = ResourceManager.GetObject("question1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin NXB thất bại !!!.
        /// </summary>
        public static string UPDATE_PUBLISHER_FAIL {
            get {
                return ResourceManager.GetString("UPDATE_PUBLISHER_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin NXB thành công !!!.
        /// </summary>
        public static string UPDATE_PUBLISHER_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_PUBLISHER_SUCCESS", resourceCulture);
            }
        }
    }
}
