static class HelpContextMap
{
	 public static int CID_THEM_DAU_SACH_MOI                                    = 100010; // 	Thêm đầu sách mới
     public static int CID_THAY_DOI_THONG_TIN_COA_MT_DAU_SACH = 100020; // 	Thay đổi thông tin của một đầu sách
     public static int CID_XOA_MT_DAU_SACH = 100030; // 	Xóa một đầu sách
     public static int CID_THEM_TAC_GIA = 100050; // 	Thêm tác giả
     public static int CID_THAY_DOI_THONG_TIN_COA_MT_TAC_GIA = 100060; // 	Thay đổi thông tin của một tác giả
     public static int CID_XOA_MT_TAC_GIA = 100070; // 	Xóa một tác giả
     public static int CID_THEM_MOI_MT_NXB = 100090; // 	Thêm mới một NXB
     public static int CID_THAY_DOI_THONG_TIN_COA_MT_NXB = 100100; // 	Thay đổi thông tin của một NXB
     public static int CID_XOA_MT_NXB = 100110; // 	Xóa một NXB
     public static int CID_THEM_MT_DANH_MOC = 100130; // 	Thêm một danh mục
     public static int CID_THAY_DOI_THONG_TIN_COA_MT_DANH_MOC = 100140; // 	Thay đổi thông tin của một danh mục
     public static int CID_XOA_MT_DANH_MOC = 100150; // 	Xóa một danh mục
     public static int CID_THEM_BAN_SAO = 100170; // 	Thêm bản sao
     public static int CID_XOA_BAN_SAO = 100180; // 	Xóa bản sao
     public static int CID_MOC_DICH = 100200; // 	Mục đích
     public static int CID_SU_DONG                                              = 100210; // 	Sử dụng
     public static int CID_GIAO_DIEN_CHINH                                      = 100220; // 	Giao diện chính
     public static int CID_MOC_DICH1                                            = 100250; // 			Mục đích
     public static int CID_CACH_SU_DONG                                         = 100260; // 			Cách sử dụng
     public static int CID_TAC_DONG                                             = 100270; // 			Tác dụng
	 public static int CID_TU_CHOI_YEU_CAU                                      = 100280; // 		Từ chối yêu cầu
	 public static int CID_CACH_SU_DONG1                                        = 100290; // 			Cách sử dụng
	 public static int CID_TAC_DONG1                                            = 100300; // 			Tác dụng
	 public static int CID_MOC_DICH2                                            = 100320; // 			Mục đích
	 public static int CID_CACH_SU_DONG2                                        = 100330; // 			Cách sử dụng
	 public static int CID_TAC_DONG2                                            = 100340; // 			Tác dụng
	 public static int CID_MOC_DICH3                                            = 100360; // 			Mục đích
	 public static int CID_CACH_SU_DONG3                                        = 100370; // 			Cách sử dụng
	 public static int CID_TAC_DONG3                                            = 100380; // 			Tác dụng
	 public static int CID_MOC_DICH4                                            = 100400; // 			Mục đích
	 public static int CID_CACH_SU_DONG4                                        = 100410; // 			Cách sử dụng
	 public static int CID_TAC_DONG4                                            = 100420; // 			Tác dụng
	 public static int CID_MOC_DICH5                                            = 100440; // 			Mục đích
	 public static int CID_CACH_SU_DONG5                                        = 100450; // 			Cách sử dụng
	 public static int CID_TAC_DONG5                                            = 100460; // 			Tác dụng
	 public static int CID_MOC_DICH6                                            = 100480; // 			Mục đích
	 public static int CID_CACH_SU_DONG6                                        = 100490; // 			Cách sử dụng
	 public static int CID_TAC_DONG6                                            = 100500; // 			Tác dụng
	 public static int CID_MOC_DICH7                                            = 100520; // 	Mục đích
	 public static int CID_SU_DONG1                                             = 100530; // 	Sử dụng
	 public static int CID_GIAO_DIEN_CHINH1                                     = 100540; // 	Giao diện chính
	 public static int CID_MOC_DICH8                                            = 100570; // 			Mục đích
	 public static int CID_CACH_SU_DONG7                                        = 100580; // 			Cách sử dụng
	 public static int CID_TAC_DONG7                                            = 100590; // 			Tác dụng
	 public static int CID_MOC_DICH9                                            = 100610; // 			Mục đích
	 public static int CID_CACH_SU_DONG8                                        = 100620; // 			Cách sử dụng
	 public static int CID_TAC_DONG8                                            = 100630; // 			Tác dụng
	 public static int CID_HINH_CHOP                                            = 100660; // 		Hình chụp:
	 public static int CID_MOC_DICH_SU_DONG                                     = 100670; // 		Mục đích sử dụng:
	 public static int CID_THAO_TAC                                             = 100680; // 		Thao tác:
	 public static int CID_HINH_CHOP1                                           = 100700; // 		Hình chụp:
	 public static int CID_MOC_DICH_SU_DONG1                                    = 100710; // 		Mục đích sử dụng:
	 public static int CID_THAO_TAC1                                            = 100720; // 		Thao tác:
	 public static int CID_HINH_CHOP2                                           = 100740; // 		Hình chụp:
	 public static int CID_MOC_DICH_SU_DONG2                                    = 100750; // 		Mục đích sử dụng:
	 public static int CID_CHU_THICH_HINH                                       = 100760; // 		Chú thích hình:
	 public static int CID_THAO_TAC2                                            = 100770; // 		Thao tác:
	 public static int CID_HINH_CHOP3                                           = 100790; // 		Hình chụp:
	 public static int CID_CHU_THICH_HINH1                                      = 100800; // 		Chú thích hình: 
	 public static int CID_ANH_CHOP_MAN_HINH                                    = 100820; // 		Ảnh chụp màn hình:
	 public static int CID_CAC_BUOC_THUC_HIEN                                   = 100830; // 		Các bước thực hiện:
	 public static int CID_ANH_CHOP_MAN_HINH1                                   = 100850; // 		Ảnh chụp màn hình:
	 public static int CID_CAC_BUOC_THUC_HIEN1                                  = 100860; // 		Các bước thực hiện:
	 public static int CID_ANH_CHOP_MAN_HINH2                                   = 100880; // 		Ảnh chụp màn hình:
     public static int CID_CAC_BUOC_THUC_HIEN2                                  = 100890; // 		Các bước thực hiện:
}
